name: HoverStats
version: '${project.version}'
main: me.brand0n_.hoverstats.HoverStats
api-version: 1.16
softdepend:  [ PlaceholderAPI, LPC, Vault ]
authors: [ Brand0n_ ]
description: Add a hover effect over the players message in chat saying some key stats


commands:
  hoverstats:
    description: Command used to reload the plugin

permissions:
  hoverstats.help:
    default: true
  hoverstats.join-formatting:
    default: true
  hoverstats.leave-formatting:
    default: true
  hoverstats.colors.*:
    description: This will give the player access to all chat colors
    default: false
  hoverstats.magic.*:
    description: This will give the player access to all "magic" color codes
    default: false
  hoverstats.colors.hex:
    description: This will give the player access to all hex colors
    default: false
  hoverstats.whitelist:
    default: op
  hoverstats.blacklist:
    default: op
  hoverstats.whitelist.user:
    default: op
  hoverstats.whitelist.group:
    default: op
  hoverstats.blacklist.user:
    default: op
  hoverstats.blacklist.group:
    default: op
  hoverstats.update:
    default: op
  hoverstats.version:
    default: op
  hoverstats.reload:
    default: false
  hoverstats.chat.view:
    default: false

  hoverstats.admin:
    children:
      hoverstats.help: true
      hoverstats.reload: true
      hoverstats.blacklist: true
      hoverstats.whitelist: true
      hoverstats.blacklist.user: true
      hoverstats.blacklist.group: true
      hoverstats.whitelist.user: true
      hoverstats.whitelist.group: true
      hoverstats.update: true
      hoverstats.version: true
      hoverstats.chat.view: true
      hoverstats.colors.hex: true
      hoverstats.magic.*: true
      hoverstats.colors.*: true
      hoverstats.join-formatting: true
      hoverstats.leave-formatting: true
  hoverstats.*:
    children:
      hoverstats.help: true
      hoverstats.reload: true
      hoverstats.blacklist: true
      hoverstats.whitelist: true
      hoverstats.blacklist.user: true
      hoverstats.blacklist.group: true
      hoverstats.whitelist.user: true
      hoverstats.whitelist.group: true
      hoverstats.update: true
      hoverstats.version: true
      hoverstats.chat.view: true
      hoverstats.colors.hex: true
      hoverstats.magic.*: true
      hoverstats.colors.*: true
      hoverstats.join-formatting: true
      hoverstats.leave-formatting: true

