name: HoverStats
version: '${project.version}'
main: me.brand0n_.hoverstats.HoverStats
api-version: 1.16
softdepend:  [ PlaceholderAPI ]
authors: [ Brand0n_ ]
description: Add a hover effect over the players message in chat saying some key stats


commands:
  hoverstats:
    description: Command used to reload the plugin

permissions:
  hoverstats.help:
    default: true
  hoverstats.reload:
    default: false

  hoverstats.admin:
    children:
      hoverstats.help: true
      hoverstats.reload: true
  hoverstats.*:
    children:
      hoverstats.help: true
      hoverstats.reload: true

